# -*- coding: utf-8 -*-
"""data cleaning

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eGfy-c5KRCmvTo7BatVzBTy3E5bJCNGw
"""

import pandas as pd

df=pd.read_csv("/content/drive/MyDrive/data (1) (1).csv")
print(df.head())

df.shape

print(df.to_markdown())

df.isnull()

df.isnull().sum()

df.dropna(inplace=True)

df.fillna(130,inplace=True)

print(df.to_markdown())

"""mode"""

df=pd.read_csv("/content/drive/MyDrive/data (1) (1).csv")
print(df.head())

x=df["Calories"].mode()[0]
df["Calories"].fillna(x,inplace=True)

print(df.to_markdown())

"""mean"""

df=pd.read_csv("/content/drive/MyDrive/data (1) (1).csv")
print(df.head())

x=df["Calories"].mean()
df["Calories"].fillna(x,inplace=True)

print(df.to_markdown())

"""median

"""

df=pd.read_csv("/content/drive/MyDrive/data (1) (1).csv")
print(df.head())

x=df["Calories"].median()
df["Calories"].fillna(x,inplace=True)

print(df.to_markdown())

df.corr()

print(df.duplicated())

df.drop_duplicates(inplace=True)

df.shape