# -*- coding: utf-8 -*-
"""data cleaning(2)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e8bNVEbMYOP_tlohP2U_sbXDhPEInD6h
"""

import pandas as pd
import numpy as np
from functools import reduce

df=pd.read_csv("/content/drive/MyDrive/BL-Flickr-Images-Book (1).csv")
print(df.head())

to_drop=["Edition Statement",
         "Corporate Author"]
df.drop(to_drop, inplace=True, axis=1)
df.head()

df.shape

for col in df.columns:
  print(col)

df.set_index("Identifier",inplace=True)
df.head()

unwanted_characters=['[',',','-']
def clean_dates(item):
   dop=str(item.loc['Date of Publication'])
   if dop=='nan' or dop[0]=='[':
       return np.NaN
   for character in unwanted_characters:
     if character in dop:
       character_index = dop.find(character)
       dop=dop[:character_index]
   return dop

df["Date of Publication"]=df.apply(clean_dates,axis=1)

def clean_title(title):
  if title=='nan':
    return 'NaN'
  if title[0]=='[':
    title =title[1:title.find(']')]
  if 'by'in title:
    title = title[:title.find('by')]
  if 'By' in title:
    title = title[: title.find('By')]
  if '[' in title:
     title= title[: title.find('[')]
  title= title[:-2]

df['Title'] = df['Title'].apply(clean_title)
df.head()