# -*- coding: utf-8 -*-
"""matplot

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b3L4uBixOYvajSxoh_bgkOM80-8YV3Lh
"""

import matplotlib.pyplot as plt

x=[1,2,3,4]
y=[4,5,6,7,]
plt.xlabel("x axis")
plt.ylabel("y axis")
plt.title("Line graph")
plt.plot(x,y)
plt.show()

x=(["A","B","C","D"])
Y=([2,5,1,10])
plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt
x=[20,30,40,50]
plt.pie(x)
plt.show()

import matplotlib.pyplot as plt
x=[20,30,40,50]
y=["cherries","apple","banana","mango"]
plt.pie(x, labels= y)
plt.show()

import matplotlib.pyplot as plt
x=[20,30,40,50]
y=["cherries","apple","banana","mango"]
z=[0.2,0,0,0]
plt.pie(x, labels= y ,explode=z)
plt.show()

import matplotlib.pyplot as plt
x=[20,30,40,50]
y=["cherries","apple","banana","mango"]
z=[0.2,0,0,0]
plt.pie(x, labels= y ,explode=z,shadow="true")
plt.show()

x=(["A","B","C","D"])
Y=([2,5,1,10])
plt.scatter(x,y,color="r")
plt.show()

x=([2,4,6,8])
y=([1,3,5,7])
z=(["pink","blue","black","red"])
sizes=[200,300,480,380]
plt.scatter(x,y,color=z, marker="*",edgecolor="green",s=sizes,alpha=1)
plt.title("Scatter graph")
plt.xlabel("X axis")
plt.ylabel("Y axis")
plt.show()

import matplotlib.pyplot as plt
g=[2,4,6,8]
h=[1,3,5,7]

plt.subplot(2,2,1)

plt.plot(g,h)
plt.subplot(2,2,2)

x=[20,30,40,50]
y=["cherries","apple","banana","mango"]
plt.pie(x, labels= y)
plt.subplot(2,2,3)

x=(["A","B","C","D"])
y=([2,5,1,10])
plt.bar(x,y)
plt.subplot(2,2,4)

x=([1,2,3,4])
y=([1,2,3,4])
z=(["pink","blue","black","red"])
sizes=[200,300,480,380]
plt.scatter(x,y,color=z, marker="*",edgecolor="green",s=sizes,alpha=1)
plt.title("Scatter graph")
plt.xlabel("X axis")
plt.ylabel("Y axis")

