# -*- coding: utf-8 -*-
"""matrix visualization

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VA8U0vjp62mK9cQzkiZSJrEKjZGtlaSm
"""

import numpy as np
import matplotlib.pyplot as plt
data=np.random.random((13,16))
plt.imshow(data,cmap="magma")
plt.title("2-D Heat Map")
plt.colorbar()
plt.show()

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

data=np.random.randint(low=14,
          high=100,
          size=(10,10))
hm=sns.heatmap(data=data,annot=True)
plt.show()

import plotly.express as px
df=px.data.tips()
fig=px.treemap(df,path=[px.Constant("all"),'sex','day','time'],values='total_bill',color='day')
fig.update_layout(margin=dict(t=50,l=25,r=25,b=25))
fig.show()