# -*- coding: utf-8 -*-
"""pandas series

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HOyYh2PuGIvKXjGKLpJ8y5yxOY4t33rz
"""

import pandas as pd
a=[1,7.2,2]
s1=pd.Series(a)
print(s1)

print(s1[0])

a=[1,7,2]
s1=pd.Series(a,index=["x","y","z"])
print(s1)
print(s1["y"])

import pandas as pd
s1=pd.Series([-3,-1,1,3,5,'Aditya',7.3])
print(s1)

"""slicing"""

s1[:2]

print(s1[2])

"""create labels"""

a=[1,7,2]
s1=pd.Series(a,index=["x","y","z"])
print(s1)

"""creating series from dictionary"""

calories={'day 1':420,'day 2':380,'day 3':390}
s1=pd.Series(calories)
print(s1)

print(s1[[2,1,0]])

type(s1)

s=pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
print(s['a'])

data={
    'Calories':[420,380,390,400,200],
    'Maxpulse':[89,90,98,70,80],
    'Duration':[50,40,45,50,48]
}
df=pd.DataFrame(data)
print(df)

import pandas as pd
data={'Name':['Tom','Jack','Steve','Ricky'],
      'Age':[28,34,29,42]}
df=pd.DataFrame(data, index=['Rank 1','Rank 2','Rank 3','Rank 4'])
print(df)

print(s1.loc["day 2"])

df.info

df.dtypes

df.columns

df.size

df.describe()

df['Id']=[10,10,20,40]
print(df)

df['Id'].unique()

df['Id'].value_counts()